;1、域名组
ruleset=✨ AI,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/AI.list
ruleset=📘 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
ruleset=👯‍♂️ TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=🙋 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🕊️ Twitter(X),https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list
ruleset=🗣️ Facebook,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.list
ruleset=🌳 Amazon,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Amazon/Amazon.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🎮 Steam,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list
ruleset=🎞️ YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=📺 Disney,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🎵 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=🌍 国外,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/Proxy.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list
ruleset=➡️ 国内,[]FINAL

;2、策略组（域名组-节点组）
custom_proxy_group=✨ AI`select`[]DIRECT`[]GPT-自动`[]REJECT
custom_proxy_group=📘 GitHub`select`[]DIRECT`[]所有-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]其他-自动`[]REJECT
custom_proxy_group=👯‍♂️ TikTok`select`[]DIRECT`[]所有-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]其他-自动`[]REJECT
custom_proxy_group=🙋 Telegram`select`[]DIRECT`[]所有-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]其他-自动`[]REJECT
custom_proxy_group=🕊️ Twitter(X)`select`[]DIRECT`[]所有-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]其他-自动`[]REJECT
custom_proxy_group=🗣️ Facebook`select`[]DIRECT`[]所有-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]其他-自动`[]REJECT
custom_proxy_group=🌳 Amazon`select`[]DIRECT`[]所有-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]其他-自动`[]REJECT
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]所有-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]其他-自动`[]REJECT
custom_proxy_group=Ⓜ️ Microsoft`select`[]DIRECT`[]所有-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]其他-自动`[]REJECT
custom_proxy_group=🎮 Steam`select`[]DIRECT`[]所有-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]其他-自动`[]REJECT
custom_proxy_group=🕹️ Game`select`[]DIRECT`[]所有-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]其他-自动`[]REJECT
custom_proxy_group=🎞️ YouTube`select`[]媒体-自动`[]REJECT
custom_proxy_group=📺 Disney`select`[]媒体-自动`[]REJECT
custom_proxy_group=🎥 Netflix`select`[]媒体-自动`[]REJECT
custom_proxy_group=🎵 Spotify`select`[]媒体-自动`[]REJECT
custom_proxy_group=🌍 国外`select`[]DIRECT`[]所有-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]其他-自动`[]REJECT
custom_proxy_group=➡️ 国内`select`[]DIRECT`[]所有-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]其他-自动`[]REJECT

;3、节点组
custom_proxy_group=所有-自动`url-test`.*`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=GPT-自动`url-test`GPT`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=IPLC-自动`url-test`IPLC`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=媒体-自动`url-test`媒体`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=香港-自动`url-test`((IPLC).*(港))`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=台湾-自动`url-test`((IPLC).*(台))`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=日本-自动`url-test`((IPLC).*(日))`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=新加坡-自动`url-test`((IPLC).*(新))`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=美国-自动`url-test`((IPLC).*(美))`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=其他-自动`url-test`(直连|特殊)`http://www.gstatic.com/generate_204`60,150

;4、启用规则集
enable_rule_generator=true
overwrite_original_rules=true
